name: CI Pipeline

# Déclencher le workflow à chaque push sur la branche develop
on:
  push:
    branches:
      - develop

jobs:
  test-memory:
    # Utiliser un runner self-hosted
    runs-on: self-hosted

    steps:
      # Étape 1 : Vérification du code source
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2 : Vérification des fichiers JPEG
      - name: Test JPEG files for corruption
        run: |
          echo "Checking for corrupted JPEG files..."
          for file in $(find . -type f -name "*.jpg"); do
            echo "Checking $file"
            file $file | grep -q "JPEG image data" || {
              echo "$file is corrupted. Replacing it..."
              # Remplacer le fichier corrompu par un autre fichier 
              cp html/data/1.jpg $file
            }
          done


  build-memory:
    # Ce job ne s'exécute qu'après la réussite du job 'test-memory'
    runs-on: self-hosted
    needs: test-memory

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/memory .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/memory
